swagger: '2.0'
info:
  description: '企业微信服务端API.'
  version: 1.0.0
  title: 企业微信服务端API
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
host: qyapi.weixin.qq.com
basePath: /cgi-bin
tags:
  - name: token
    description: 
schemes:
  - https
paths:
  /gettoken:
    get:
      tags:
        - token
      summary: 每个应用有独立的secret，获取到的access_token只能本应用使用，所以每个应用的access_token应该分开来获取
      description: ''
      operationId: gettoken
      produces:
        - application/json
      parameters:
        - in: query
          name: corpid
          description: 企业ID
          required: true
          type: string
        - in: query
          name: corpsecret
          description: 应用的凭证密钥
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/TokenRsp'
  /get_api_domain_ip:
    get:
      tags:
        - token
      summary: 获取企业微信API域名IP段
      description: ''
      operationId: get_api_domain_ip
      produces:
        - application/json
      parameters:
        - in: query
          name: access_token
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/GetApiDomainIpRsp'
  /user/create:
    post:
      tags:
        - user
      summary: 创建成员
      description: 创建成员
      operationId: create
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: access_token
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/CreateUserReq'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/BaseResponse'
  /user/get:
    get:
      tags:
        - user
      summary: 读取成员
      description: 读取成员
      operationId: get
      produces:
        - application/json
      parameters:
        - in: query
          name: access_token
          required: true
          type: string
        - in: query
          name: userid
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/GetUserRsp'
  /user/update:
    post:
      tags:
        - user
      summary: 更新成员
      description: 更新成员
      operationId: update
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/UpdateUserReq'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/BaseResponse'
  /user/delete:
    get:
      tags:
        - user
      summary: 删除成员
      description: 删除成员
      operationId: delete
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: access_token
          required: true
          type: string
        - in: query
          name: userid
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/BaseResponse'
  /user/batchdelete:
    post:
      tags:
        - user
      summary: 批量删除成员
      description: 批量删除成员
      operationId: batchdelete
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/BatchDeleteUserReq'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/BaseResponse'
  /user/simplelist:
    get:
      tags:
        - user
      summary: 获取部门成员
      description: 获取部门成员
      operationId: simplelist
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: access_token
          type: string
          required: true
        - in: query
          name: department_id
          required: true
          type: integer
          format: int32
        - in: query
          name: fetch_child
          required: false
          type: integer
          format: int32
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/SimplelistRsp'
  /user/list:
    get:
      tags:
        - user
      summary: 获取部门成员详情
      description: 获取部门成员详情
      operationId: list
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: access_token
          required: true
          type: string
          description: 调用接口凭证
        - in: query
          name: department_id
          required: true
          type: integer
          format: int32
          description: 获取的部门id
        - in: query
          name: fetch_child
          required: false
          type: integer
          format: int32
          description: 1/0：是否递归获取子部门下面的成员
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ListUserRsp'
  /user/convert_to_openid:
    post:
      tags:
        - user
      summary: userid与openid互换
      description: userid转openid
      operationId: convert_to_openid
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/ConvertToOpenidReq'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ConvertToOpenidRsp'
definitions:
  ConvertToOpenidReq:
    properties:
      userid:
        type: string
  ConvertToOpenidRsp:
    allOf:
      - $ref: '#/definitions/BaseResponse'
      - type: object
        properties:
          openid:
            type: string
  ListUserRsp:
    description: ListUserRsp
    allOf:
      - $ref: '#/definitions/BaseResponse'
      - type: object
        properties:
          userlist:
            type: array
            items:
              schema: '#/definitions/User'
  SimplelistRsp:
    description: SimplelistRsp
    allOf:
      - $ref: '#/definitions/BaseResponse'
      - type: object
        properties:
          userlist:
            type: array
            items:
              schema:
                userid:
                  type: string
                name:
                  type: string
                department:
                  type: array
                  items:
                    type: integer
                    format: int32
                open_userid:
                  type: string
  BatchDeleteUserReq:
    title: BatchDeleteUserReq
    description: BatchDeleteUserReq
    type: object
    properties:
      useridlist:
        type: array
        items:
          type: string
  UpdateUserReq:
    title: UpdateUserReq
    description: UpdateUserReq
    type: object
    properties:
      userid:
        type: string
      name:
        type: string
      department:
        type: array
        items:
          type: integer
          format: int32
      order:
        type: array
        items:
          type: integer
          format: int32
      position:
        type: string
      mobile:
        type: string
      gender:
        type: integer
        format: int32
      email:
        type: string
      is_leader_in_dept:
        type: array
        items:
          type: integer
          format: int32
      enable:
        type: integer
        format: int32
      avatar_mediaid:
        type: string
      telephone:
        type: string
      alias:
        type: string
      address:
        type: string
      main_department:
        type: integer
        format: int32
      extattr:
        type: object
        schema:
          $ref: '#/definitions/ExtAttrs'
      external_position:
        type: string
      external_profile:
        type: object
        schema:
          $ref: '#/definitions/ExternalProfile'
  GetUserRsp:
    allOf:
    - $ref: '#/definitions/User'
    - $ref: '#/definitions/BaseResponse'
  User:
    title: User
    description: User
    type: object
    properties:
      userid:
        type: string
        description: 成员UserID。对应管理端的帐号，企业内必须唯一。不区分大小写，长度为1~64个字节。只能由数字、字母和“_-@.”四种字符组成，且第一个字符必须是数字或字母。
      name:
        type: string
        description: 成员名称。长度为1~64个utf8字符
      department:
        type: array
        items:
          type: integer
          format: int32
        description: 成员所属部门id列表,不超过20个
      order:
        description: 部门内的排序值
        type: array
        items:
          type: integer
          format: int32
      position:
        type: string
        description: 职务信息
      mobile:
        type: string
        description: 手机号码。企业内必须唯一，mobile/email二者不能同时为空
      gender:
        type: integer
        format: int32
        description: 性别
      email:
        type: string
        description: 邮箱
      is_leader_in_dept:
        type: integer
        format: int32
        description: 个数必须和参数department的个数一致
      avatar:
        type: string
        description: 成员头像的mediaid
      thumb_avatar:
        type: string
        description: 头像缩略图url
      telephone:
        type: string
        description: 座机
      alias:
        type: string
        description: 成员别名。长度1~32个utf8字符
      address:
        type: string
        description: 地址
      open_userid:
        type: string
        description: 全局唯一。对于同一个服务商，不同应用获取到企业内同一个成员的open_userid是相同的，最多64个字节。仅第三方应用可获取
      main_department:
        type: string
        description: 主部门
      status:
        type: integer
        format: int32
        description: 激活状态 1=已激活，2=已禁用，4=未激活，5=退出企业。
      qr_code:
        type: string
        description: 员工个人二维码，扫描可添加为外部联系人(注意返回的是一个url，可在浏览器上打开该url以展示二维码)；第三方仅通讯录应用可获取。
      external_position:
        type: string
        description: 对外职务
      external_profile:
        type: object
        schema:
          $ref: '#/definitions/ExternalProfile'
        description: 成员对外属性
      extattr:
        type: object
        description: 自定义字段
        schema:
          $ref: '#/definitions/ExtAttrs'
  ExternalProfile:
    title: ExternalProfile
    description: ExternalProfile
    type: object
    properties:
      external_corp_name:
        type: string
      external_attr:
        type: array
        items:
          $ref: '#/definitions/ExtAttr'
  CreateUserReq:
    title: CreateUserReq
    description: CreateUserReq
    type: object
    properties:
      userid:
        type: string
        description: 成员UserID。对应管理端的帐号，企业内必须唯一。不区分大小写，长度为1~64个字节。只能由数字、字母和“_-@.”四种字符组成，且第一个字符必须是数字或字母。
      name:
        type: string
        description: 成员名称。长度为1~64个utf8字符
      alias:
        type: string
        description: 成员别名。长度1~32个utf8字符
      mobile:
        type: string
        description: 手机号码。企业内必须唯一，mobile/email二者不能同时为空
      department:
        type: array
        items:
          type: integer
          format: int32
        description: 成员所属部门id列表,不超过20个
      order:
        description: 部门内的排序值
        type: array
        items:
          type: integer
          format: int32
      position:
        type: string
        description: 职务信息
      gender:
        type: integer
        format: int32
        description: 性别
      email:
        type: string
        description: 邮箱
      telephone:
        type: string
        description: 座机
      is_leader_in_dept:
        type: integer
        format: int32
        description: 个数必须和参数department的个数一致
      avatar_mediaid:
        type: string
        description: 成员头像的mediaid
      enable:
        type: integer
        format: int32
        description: 启用/禁用成员。1表示启用成员，0表示禁用成员
      extattr:
        type: object
        description: 自定义字段
        schema:
          $ref: '#/definitions/ExtAttrs'
  ExtAttrs:
    title: ExtAttrs
    type: object
    properties:
      attrs:
        type: array
        items:
          $ref: '#/definitions/ExtAttr'
  ExtAttr:
    title: ExtAttr
    type: object
    properties:
      type:
        type: integer
        format: int32
      name:
        type: string
      text:
        type: map
      web:
        type: map
  TokenRsp:
    allOf:
    - $ref: '#/definitions/BaseResponse'
    title: TokenRsp
    description: TokenRsp
    type: object
    properties:
      access_token:
        type: string  
      expires_in:
        type: integer
        format: int64
  GetApiDomainIpRsp:
    allOf:
    - $ref: '#/definitions/BaseResponse'
    title: GetApiDomainIpRsp
    description: GetApiDomainIpRsp
    type: object
    properties:
      ip_list:
        type: array
        items:
          type: string
  BaseResponse:
    title: 
    description: 
    type: object
    properties:
      errcode:
        type: string
      errmsg:
        type: string